{% set name = "yfinance" %}
{% set version = "0.2.51" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/yfinance-{{ version }}.tar.gz
  sha256: 7902cc9b23699a51efa50f1cc7a965220a56beccc00d189f929b4c7c5c189a60

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - platformdirs >=2.0.0
    - python >={{ python_min }}
    - pandas >=1.3.0
    - numpy >=1.16.5
    - requests >=2.31
    - multitasking >=0.0.7
    - lxml >=4.9.1
    - appdirs >=1.4.4
    - pytz >=2022.5
    - frozendict >=2.3.4
    - peewee >=3.16.2
    - beautifulsoup4 >=4.11.1
    - html5lib >=1.1

test:
  imports:
    - yfinance
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ranaroussi/yfinance
  summary: Download market data from Yahoo! Finance API
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jan-janssen
    - timkpaine
